---
language: go
services:
  - docker
jobs:
  fast_finish: true
  include:
    - stage: build-test
      script:
      - go build
    - stage: docker
      script:
      - '[[ $TRAVIS_TAG != "" ]] && bash .travis.docker.sh || echo "passed"'

